"""add profile picture URL to user model

Revision ID: fe028940e19b
Revises: 55b7ea533e94
Create Date: 2017-02-01 08:26:51.901113

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils.types.url


# revision identifiers, used by Alembic.
revision = 'fe028940e19b'
down_revision = '55b7ea533e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_url', sqlalchemy_utils.types.url.URLType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('picture_url')

    # ### end Alembic commands ###
